USE_CCACHE=1

ESP_ADDR ?= <dns name of target>
# let it default ESP_PORT ?= 8266
# or 3232 for esp32
ESP_PWD ?= <ota flash password>
BOARD ?= d1_mini

WIFI_SSID ?= <primary ssid>
WIFI_SSID2 ?= <failover ssid>  # the dedicated SSID on your second closest AP so that it finds a different AP when locked onto the common SSID you have configured for the primary (see README)
WIFI_PASSWD ?= <wifi wpa2 passphrase (for both primary and failover)>

SYSLOG ?= <syslog ip address>

EXCLUDE_DIRS ?= $(wildcard $(ARDUINO_LIBS)/ESP32_AnalogWrite)

BUILD_EXTRA_FLAGS=-D_SSID=\"$(WIFI_SSID)\" -D_SSID2=\"$(WIFI_SSID2)\" -D_PWD=\"$(WIFI_PASSWD)\" -D_SYSLOG=\"$(SYSLOG)\" -D_OTA_PWD=\"$(ESP_PWD)\" -D_HOSTNAME=\"$(ESP_ADDR)\"

# see /home/tconnors/Arduino/makeEspArduino/README.md :
#LIBS=
#CUSTOM_LIBS=

UPLOAD_PORT ?= $(shell ls -1tr /dev/tty*USB* 2>/dev/null | tail -1)
UPLOAD_PORT := $(if $(UPLOAD_PORT),$(UPLOAD_PORT),/dev/ttyS0)
UPLOAD_VERB ?= -v

OTA_ADDR ?= $(ESP_ADDR)
OTA_PWD ?= $(ESP_PWD)

# comes from https://github.com/plerup/makeEspArduino.git
include $(HOME)/Arduino/makeEspArduino/makeEspArduino.mk

#.DEFAULT_GOAL := ota
.DEFAULT_GOAL := flash
